In [ ]:
from google.colab import drive
import os

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# Path
path = "/content/drive/My Drive/"

In [ ]:
os.chdir("/content/drive/My Drive")


In [ ]:
import os
import pandas as pd
ham_dir = "/content/drive/My Drive/NLP Project/input/ham-and-spam-dataset/ham" # Training dataset folder
spam_dir = "/content/drive/My Drive/NLP Project/input/ham-and-spam-dataset/spam" # Testing dataset folder
# Create a list containing all the words present in the training set emails
ham_emails = [os.path.join(ham_dir,f) for f in os.listdir(ham_dir)] # Gives us a path to all the messages stored in text files
spam_emails = [os.path.join(spam_dir,f) for f in os.listdir(spam_dir)]

**DATA PREPROCESSING**

In [ ]:
import nltk
import re
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

In [ ]:
path = '/content/drive/My Drive/NLP Project/input/ham-and-spam-dataset/hamnspam/'
mails = []
labels = []

for label in ['ham/', 'spam/']:
#     filenames = os.listdir(os.path.join(path, label))
    filenames = os.listdir(path + label)
    for file in filenames:
        f = open((path + label + file), 'r', encoding = 'latin-1')
        bolk = f.read()
        mails.append(bolk)
        labels.append(label)
        
df = pd.DataFrame({'emails': mails, 'labels': labels})

In [ ]:
from sklearn.preprocessing import LabelEncoder
one_coder = LabelEncoder()
df['labels'] = one_coder.fit_transform(df['labels'])

In [ ]:
df

emails  labels
0     Return-Path: tim.one@comcast.net\nDelivery-Dat...       0
1     From spamassassin-talk-admin@lists.sourceforge...       0
2     From spamassassin-talk-admin@lists.sourceforge...       0
3     From spamassassin-commits-admin@lists.sourcefo...       0
4     From easmith@beatrice.rutgers.edu  Thu Sep 26 ...       0
...                                                 ...     ...
3047  From 2002biz2biz2513@Flashmail.com  Mon Oct  7...       1
3048  From biz2biz2446@Flashmail.com  Mon Oct  7 22:...       1
3049  From cna@insiq.us  Tue Oct  8 00:10:39 2002\nR...       1
3050  From OWNER-NOLIST-SGODAILY*JM**NETNOTEINC*-COM...       1
3051  From evtwqmigru@datcon.co.uk  Tue Oct  8 11:02...       1

[3052 rows x 2 columns]

In [ ]:
df = df.drop_duplicates()

In [ ]:
def remove_special_char(text):
    new_text = ""
    for i in text.split():
        if i.isalpha():
            new_text = new_text + " " + i
        
    return new_text

In [ ]:
df['emails'] = df['emails'].apply(lambda x:x.lower())
df['emails'] = df['emails'].apply(lambda x:x.replace('\n', " "))
df['emails'] = df['emails'].apply(lambda x:x.replace('\t', " "))
df['emails'] = df['emails'].apply(remove_special_char)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documen

In [ ]:
df

emails  labels
0      fri sep sep test any thought to wrapping up y...       0
1      from tue sep from localhost by with esmtp id ...       0
2      from thu aug from localhost by with esmtp id ...       0
3      from thu aug from localhost by with esmtp id ...       0
4      from thu sep from localhost by with esmtp id ...       0
...                                                 ...     ...
3047   from mon oct from localhost by with esmtp id ...       1
3048   from mon oct from localhost by with esmtp id ...       1
3049   from tue oct from localhost by with esmtp id ...       1
3050   from thu sep from localhost by with esmtp id ...       1
3051   from tue oct from localhost by with esmtp id ...       1

[3047 rows x 2 columns]

In [ ]:
X = cv.fit_transform(df['emails']).toarray()

In [ ]:
X.shape

(3047, 2500)

In [ ]:
y = df['labels'].values

In [ ]:
y

array([0, 0, 0, ..., 1, 1, 1])

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test, = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
pip install tensorflow-text

     |████████████████████████████████| 4.9 MB 14.5 MB/s 
     |████████████████████████████████| 462 kB 52.5 MB/s 


In [ ]:
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text

In [ ]:
df['labels'].value_counts()

0    2550
1     497
Name: labels, dtype: int64

In [ ]:
497/2550

0.19490196078431374

**19% spam emails, 81% ham emails: This indicates class imbalance**




In [ ]:
df_spam = df[df['labels']==1]
df_spam.shape

(497, 2)

In [ ]:
df_ham = df[df['labels']==0]
df_ham.shape

(2550, 2)

In [ ]:
df_ham_downsampled = df_ham.sample(df_spam.shape[0])
df_ham_downsampled.shape

(497, 2)

In [ ]:
df_balanced = pd.concat([df_ham_downsampled, df_spam])
df_balanced.shape

(994, 2)

In [ ]:
df_balanced['labels'].value_counts()

0    497
1    497
Name: labels, dtype: int64

In [ ]:
df_balanced['spam']=df_balanced['labels'].apply(lambda x: 1 if x==1 else 0)
df_balanced.sample(5)

emails  labels  spam
1989   from thu sep from localhost by with esmtp id ...       0     0
2614   from fri aug from localhost by with esmtp id ...       1     1
878    from sun oct from localhost by with esmtp id ...       0     0
2710   from mon sep from localhost by with esmtp id ...       1     1
239    from tue sep from localhost by with esmtp id ...       0     0

Split the dataset into train and test

In [ ]:
from sklearn.model_selection import train_test_split

# X_train,X_test,y_train,y_test, = train_test_split(X,y,test_size=0.2,random_state=42)

X_train, X_test, y_train, y_test = train_test_split(df['emails'],df['labels'])

NAIVE BAYES

In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns
from tqdm import tqdm
from matplotlib import pyplot as plt # show graph
import re

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
from sklearn.feature_extraction.text import CountVectorizer

import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, LSTM, Dropout, Bidirectional

import os
import email
from bs4 import BeautifulSoup

In [ ]:
path = '/content/drive/My Drive/NLP Project/input/ham-and-spam-dataset/hamnspam/'

topics = []
contents = []
labels = []
num_mails = []
content_types = []

count = 0
error = 0
wrongContentType = 0
for label in ['ham', 'spam']:
    filenames = os.listdir(path + label + '/')
    for filename in filenames:
        count +=1
        labels.append(1 if label == 'spam' else 0)
        with open(os.path.join(path + label + '/', filename), 'rb') as file:
            email_file = email.parser.BytesParser(policy=email.policy.default).parse(file)
            payload = email_file.get_payload()
            num_mails.append(1 if not isinstance(payload, list) else len(payload))
            try:
                if email_file.get_content_type() == 'text/plain':
                    contents.append(email_file.get_content())
                elif email_file.get_content_type() == 'text/html':
                    contents.append(BeautifulSoup(email_file.get_content()).body.text)
                else:
                    wrongContentType += 1
                    contents.append('')
                topics.append(email_file['Subject'])
                content_types.append(email_file.get_content_type())
            except LookupError:
                error +=1
                topics.append(None)
                contents.append('')
                content_types.append('')
                pass
        
inputDF = pd.DataFrame({'topic': topics, 'content': contents, 'label': labels, 'num_mails_in_flow': num_mails, 'content_type': content_types})
print('# processed message: %d', count)
print('# failed-parsed message: %d', error)
print('# non-text message: %d', wrongContentType)

# processed message: %d 3052
# failed-parsed message: %d 3
# non-text message: %d 196


In [ ]:
inputDF.describe()

label  num_mails_in_flow
count  3052.000000        3052.000000
mean      0.164155           1.050131
std       0.370477           0.224178
min       0.000000           1.000000
25%       0.000000           1.000000
50%       0.000000           1.000000
75%       0.000000           1.000000
max       1.000000           3.000000

In [ ]:
inputDF.head(5)


topic  \
0                             [Spambayes] test sets?   
1             [SAtalk] "Broken Pipe" on initial test   
2                   Re: [SAtalk] O.T. Habeus -- Why?   
3  [SACVS] CVS: spamassassin configure,1.1.2.1,1....   
4  Re: GA Development (was Re: [SAdev] [Bug 1030]...   

                                             content  label  \
0  [Skip Montanaro]\n> Any thought to wrapping up...      0   
1  Hi\n\nI've just installed SpamAssassin and rel...      0   
2  \nOn Wednesday, August 28, 2002, at 01:50  PM,...      0   
3  Update of /cvsroot/spamassassin/spamassassin\n...      0   
4  On Sep 25,  7:35pm, Daniel Quinlan wrote:\n> A...      0   

   num_mails_in_flow content_type  
0                  1   text/plain  
1                  1   text/plain  
2                  1   text/plain  
3                  1   text/plain  
4                  1   text/plain

In [ ]:
inputDF.loc[inputDF['content_type'] == 'text/html'].head(5)


topic  \
2558  Conference calls/best quality/$.18 per minute!   
2560                Let me know what you think!32482   
2562                        Mothers you want to fuck   
2569                     Incredible Pictures!!!!!!!!   
2572  - Custom Websites for $399 Complete! (1709D@5)   

                                                content  label  \
2558  \n\n\n\n\n\nConferencing Made Easy\nOnly 18 Ce...      1   
2560  \n\n__________________________________________...      1   
2562  \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...      1   
2569  \nDo you like Sexy Animals doing the wild thin...      1   
2572  \n\n\n\n\n\nBeautiful, 100% Custom \n      Web...      1   

      num_mails_in_flow content_type  
2558                  1    text/html  
2560                  1    text/html  
2562                  1    text/html  
2569                  1    text/html  
2572                  1    text/html

In [ ]:
# It seems that an email of 'text/html' is likely to be a spam.


inputDF.loc[inputDF['content_type'].str.startswith('multipart')].head(5)


topic content  label  \
9               Re: [Razor-users] Razor with sendmail              0   
17  Re: [SAtalk] Getting yourself removed from spa...              0   
49                   Re: [SAtalk] O.T. Habeus -- Why?              0   
61          Re: [SAtalk] Still confused about spamd/c              0   
95                             [SAtalk] spamc and DCC              0   

    num_mails_in_flow           content_type  
9                   2       multipart/signed  
17                  2       multipart/signed  
49                  2       multipart/signed  
61                  2       multipart/signed  
95                  2  multipart/alternative

In [ ]:
inputDF['topic_content'] = inputDF.topic.astype('U') + " " + inputDF.content
inputDF.topic_content

0       [Spambayes] test sets? [Skip Montanaro]\n> Any...
1       [SAtalk] "Broken Pipe" on initial test Hi\n\nI...
2       Re: [SAtalk] O.T. Habeus -- Why? \nOn Wednesda...
3       [SACVS] CVS: spamassassin configure,1.1.2.1,1....
4       Re: GA Development (was Re: [SAdev] [Bug 1030]...
                              ...                        
3047    FWD:Direct marketing is working               ...
3048    See your Company sales sky rocket.            ...
3049                               Hit the Road with CNA 
3050    MAKE MONEY GIVING AWAY FREE STUFF! \n\n\n\n\n\...
3051    Faeries UNCOMMON EXOTIC PLEASURE BOTANICALS!\n...
Name: topic_content, Length: 3052, dtype: object

In [ ]:
y = inputDF.label
X = inputDF.topic_content
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42, stratify=y, shuffle=True)
X_train.shape, X_test.shape

((2044,), (1008,))

In [ ]:
def reportTest(y_pred, y_test):
    print("Classification report:")
    print(classification_report(y_test, y_pred))
    print("Confusion matrix:")
    print(confusion_matrix(y_test, y_pred))

    print("The accuracy is {}".format(accuracy_score(y_test, y_pred))) 
    print("The precision is {}".format(precision_score(y_test, y_pred))) 
    print("The recall is {}".format(recall_score(y_test, y_pred))) 
    print("The F1-Score is {}".format(f1_score(y_test, y_pred))) 
    print("The AUC is {} ".format(roc_auc_score(y_test, y_pred)))

In [ ]:
def get_strategy():
    try:
        tpu_cluster_resolver = tf.distribute.cluster_resolver.TPUClusterResolver()  # TPU detection
        print('Running on TPU ', tpu_cluster_resolver.cluster_spec().as_dict()['worker'])
        tf.config.experimental_connect_to_cluster(tpu_cluster_resolver)
        tf.tpu.experimental.initialize_tpu_system(tpu_cluster_resolver)
        strategy = tf.distribute.experimental.TPUStrategy(tpu_cluster_resolver)
    except ValueError as e:
        print(e)
        print('No TPU detected')
        tpu = None
        strategy = tf.distribute.get_strategy()
    return strategy

strategy = get_strategy()

Running on TPU  ['10.71.242.82:8470']
INFO:tensorflow:Deallocate tpu buffers before initializing tpu system.


INFO:tensorflow:Deallocate tpu buffers before initializing tpu system.


INFO:tensorflow:Initializing the TPU system: grpc://10.71.242.82:8470


INFO:tensorflow:Initializing the TPU system: grpc://10.71.242.82:8470


INFO:tensorflow:Finished initializing TPU system.


INFO:tensorflow:Finished initializing TPU system.


INFO:tensorflow:Found TPU system:


INFO:tensorflow:Found TPU system:


INFO:tensorflow:*** Num TPU Cores: 8


INFO:tensorflow:*** Num TPU Cores: 8


INFO:tensorflow:*** Num TPU Workers: 1


INFO:tensorflow:*** Num TPU Workers: 1


INFO:tensorflow:*** Num TPU Cores Per Worker: 8


INFO:tensorflow:*** Num TPU Cores Per Worker: 8


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:0, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:0, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:1, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:1, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:2, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:2, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:3, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:3, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:4, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:4, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:5, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:5, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:6, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:6, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:7, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:7, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 0, 0)


MultinomialNB

In [ ]:
# cv = CountVectorizer(stop_words = {'english'}, ngram_range=(1, 3))
cv = CountVectorizer(max_features=2500,stop_words="english")
feature_word_train = cv.fit_transform(X_train).toarray()
feature_word_test = cv.transform(X_test).toarray()

In [ ]:
mnb = MultinomialNB()

def checkTest(clf, X_test, y_test):
    y_pred = clf.predict(X_test)
    reportTest(y_pred, y_test)

for clf, clf_name in [(mnb, 'MultinomialNB')]:
    print("Training for " + clf_name)
    clf.fit(feature_word_train, y_train)
    checkTest(clf, feature_word_test, y_test)
    print("--------------------------------------------------------------\n")

Training for MultinomialNB
Classification report:
              precision    recall  f1-score   support

           0       0.96      0.99      0.98       843
           1       0.96      0.80      0.87       165

    accuracy                           0.96      1008
   macro avg       0.96      0.90      0.93      1008
weighted avg       0.96      0.96      0.96      1008

Confusion matrix:
[[838   5]
 [ 33 132]]
The accuracy is 0.9623015873015873
The precision is 0.9635036496350365
The recall is 0.8
The F1-Score is 0.8741721854304637
The AUC is 0.8970344009489917 
--------------------------------------------------------------



In [ ]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB,ComplementNB

gnb = GaussianNB()

def checkTest(clf, X_test, y_test):
    y_pred = clf.predict(X_test)
    reportTest(y_pred, y_test)

for clf, clf_name in [(gnb, 'GaussianNB')]:
    print("Training for " + clf_name)
    clf.fit(feature_word_train, y_train)
    checkTest(clf, feature_word_test, y_test)
    print("--------------------------------------------------------------\n")

Training for GaussianNB
Classification report:
              precision    recall  f1-score   support

           0       0.96      0.98      0.97       843
           1       0.87      0.82      0.84       165

    accuracy                           0.95      1008
   macro avg       0.92      0.90      0.91      1008
weighted avg       0.95      0.95      0.95      1008

Confusion matrix:
[[823  20]
 [ 30 135]]
The accuracy is 0.9503968253968254
The precision is 0.8709677419354839
The recall is 0.8181818181818182
The F1-Score is 0.84375
The AUC is 0.897228512886876 
--------------------------------------------------------------



In [ ]:
bnb = BernoulliNB()

def checkTest(clf, X_test, y_test):
    y_pred = clf.predict(X_test)
    reportTest(y_pred, y_test)

for clf, clf_name in [(bnb, 'BernoulliNB')]:
    print("Training for " + clf_name)
    clf.fit(feature_word_train, y_train)
    checkTest(clf, feature_word_test, y_test)
    print("--------------------------------------------------------------\n")

Training for BernoulliNB
Classification report:
              precision    recall  f1-score   support

           0       0.93      0.98      0.96       843
           1       0.88      0.64      0.74       165

    accuracy                           0.93      1008
   macro avg       0.90      0.81      0.85      1008
weighted avg       0.92      0.93      0.92      1008

Confusion matrix:
[[828  15]
 [ 59 106]]
The accuracy is 0.9265873015873016
The precision is 0.8760330578512396
The recall is 0.6424242424242425
The F1-Score is 0.7412587412587414
The AUC is 0.8123153240590963 
--------------------------------------------------------------



In [ ]:
cnb = ComplementNB()

def checkTest(clf, X_test, y_test):
    y_pred = clf.predict(X_test)
    reportTest(y_pred, y_test)

for clf, clf_name in [(cnb, 'ComplementNB')]:
    print("Training for " + clf_name)
    clf.fit(feature_word_train, y_train)
    checkTest(clf, feature_word_test, y_test)
    print("--------------------------------------------------------------\n")

Training for ComplementNB
Classification report:
              precision    recall  f1-score   support

           0       0.98      0.99      0.98       843
           1       0.96      0.87      0.91       165

    accuracy                           0.97      1008
   macro avg       0.97      0.93      0.95      1008
weighted avg       0.97      0.97      0.97      1008

Confusion matrix:
[[837   6]
 [ 21 144]]
The accuracy is 0.9732142857142857
The precision is 0.96
The recall is 0.8727272727272727
The F1-Score is 0.9142857142857144
The AUC is 0.9328049175024263 
--------------------------------------------------------------



LSTM model

In [ ]:
num_words = 8196

tokenizer = Tokenizer(num_words = num_words - 1, oov_token="<OOV>")
tokenizer.fit_on_texts(X_train)
seq_train_tokenized = tokenizer.texts_to_sequences(X_train)
seq_test_tokenized = tokenizer.texts_to_sequences(X_test)

In [ ]:
max_content_length = 512

trained_word_embedding = pad_sequences(seq_train_tokenized, max_content_length)
test_word_embedding = pad_sequences(seq_test_tokenized, max_content_length)

In [ ]:
tf.keras.backend.clear_session()

with strategy.scope():
    lstmModel = Sequential([
        Embedding(num_words, 256, input_length=max_content_length),
        Bidirectional(tf.keras.layers.LSTM(128, return_sequences=True)),
        Dropout(0.5),
        Bidirectional(tf.keras.layers.LSTM(64)),
        Dense(16, activation="relu"),
        Dropout(0.5),
        Dense(2, activation='softmax')
    ])

    lstmModel.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=3e-5, epsilon=1e-08, clipnorm=1.0), 
                      loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True), 
                      metrics=[tf.keras.metrics.SparseCategoricalAccuracy('accuracy')])
    # lstmModel.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])
    lstmModel.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 512, 256)          2098176   
                                                                 
 bidirectional (Bidirectiona  (None, 512, 256)         394240    
 l)                                                              
                                                                 
 dropout (Dropout)           (None, 512, 256)          0         
                                                                 
 bidirectional_1 (Bidirectio  (None, 128)              164352    
 nal)                                                            
                                                                 
 dense (Dense)               (None, 16)                2064      
                                                                 
 dropout_1 (Dropout)         (None, 16)                0

In [ ]:
X_new = np.array(trained_word_embedding)
y_new = np.array(y_train)

lstmModel.fit(X_new, y_new, epochs=40, batch_size=128)


Epoch 1/40


/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py:1082: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a sigmoid or softmax activation and thus does not represent logits. Was this intended?"
  return dispatch_target(*args, **kwargs)


16/16 [==============================] - 23s 407ms/step - loss: 0.6889 - accuracy: 0.5352
Epoch 2/40
16/16 [==============================] - 7s 406ms/step - loss: 0.6554 - accuracy: 0.7402
Epoch 3/40
16/16 [==============================] - 6s 406ms/step - loss: 0.6242 - accuracy: 0.7916
Epoch 4/40
16/16 [==============================] - 6s 406ms/step - loss: 0.5902 - accuracy: 0.8151
Epoch 5/40
16/16 [==============================] - 6s 406ms/step - loss: 0.5414 - accuracy: 0.8273
Epoch 6/40
16/16 [==============================] - 6s 405ms/step - loss: 0.5182 - accuracy: 0.8322
Epoch 7/40
16/16 [==============================] - 7s 406ms/step - loss: 0.4890 - accuracy: 0.8312
Epoch 8/40
16/16 [==============================] - 6s 405ms/step - loss: 0.4746 - accuracy: 0.8312
Epoch 9/40
16/16 [==============================] - 6s 405ms/step - loss: 0.4629 - accuracy: 0.8288
Epoch 10/40
16/16 [==============================] - 6s 405ms/step - loss: 0.4462 - accuracy: 0.8346
Epoch 11/

In [ ]:
y_pred = np.argmax(lstmModel.predict(np.array(test_word_embedding)), axis=-1)
reportTest(y_pred, np.array(y_test))

Classification report:
              precision    recall  f1-score   support

           0       0.98      0.99      0.98       843
           1       0.94      0.87      0.91       165

    accuracy                           0.97      1008
   macro avg       0.96      0.93      0.94      1008
weighted avg       0.97      0.97      0.97      1008

Confusion matrix:
[[834   9]
 [ 21 144]]
The accuracy is 0.9702380952380952
The precision is 0.9411764705882353
The recall is 0.8727272727272727
The F1-Score is 0.9056603773584905
The AUC is 0.9310255580718213 
